In [9]:
#Create Acronyms using Python
phrase=input('Enter a phrase:')
text =phrase.split()
a = ''
for i in text:
  a = a + i[0].upper()
print(a)

Enter a phrase:Ajita Giri
AG


In [14]:
#Alarm clock with Python
from datetime import datetime
alarm_time = input('Enter the time of alarm to be set:HH:MM:SS\n')
alarm_hour = alarm_time[0:2]
alarm_minute = alarm_time[3:5]
alarm_seconds = alarm_time[6:8]
alarm_period = alarm_time[9:11].upper()
print('Setting up alarm.')
while True:
  now = datetime.now()
  current_hour = now.strftime('%I')
  current_minute = now.strftime('%M')
  current_seconds = now.strftime('%S')
  current_period = now.strftime('%p')
  if(alarm_period==current_period):
    if(alarm_hour==current_hour):
      if(alarm_minute==current_minute):
        if(alarm_seconds==current_seconds):
          print('Wake up!')
          break


Enter the time of alarm to be set:HH:MM:SS
08
Setting up alarm.


In [20]:
#Email Slicer
email = input('Enter your email:').strip() #.strip is used to remove any accidental leading or trailing whitespaces in email.
username=email[:email.index('@')]
domainname=email[email.index('@')+1:]
print('Your user name is',username,'and your domain is', domainname)

Enter your email:ajitagiri26@gmail.com
Your user name is ajitagiri26 and your domain name is gmail.com


In [32]:
#story generator with python
import random
when = ['A few Years ago', 'Yesterday', 'Last night', 'A long time ago', 'On 8th April']
who = ['A rabbit', 'A person']
name = ['Ali','Ajita','Deepesh']
residence = ['Barcelona', 'India','Germany','Nepal']
went = ['cinema', 'university', 'seminar', 'school']
happened = ['made a lot of friends.','Eats a burger.','wrote a book.']
print(random.choice(when)+', '+random.choice(who)+ ' that lived in '+random.choice(residence)+', went to the '+ random.choice(went) + ' and ' + random.choice(happened))

A long time ago, A rabbit that lived in Barcelona, went to the university and wrote a book.


In [34]:
#Generate password with python
import secrets
import string
def generate_password(length=14):
  characters = string.ascii_letters + string.digits + string.punctuation
  password = ''.join(secrets.choice(characters)for _ in range(length))
  return password
password = generate_password()
print("Generated Password:", password)
print(len(password))

Generated Password: (}q;2:$(;yPpR^
14


In [37]:
#Generate QR code
!pip install pyqrcode

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyqrcode: filename=PyQRCode-1.2.1-py3-none-any.whl size=36223 sha256=e85cf5086385fc2f6e647effb1bcc44a18a5efaf649d58e00b2d8ae505b91b8a
  Stored in directory: /root/.cache/pip/wheels/34/2d/20/082874e49a32cdcc87ebaf99dd0099fb7774ef30f010dfb6f2
Successfully built pyqrcode


In [41]:
import pyqrcode
from pyqrcode import QRCode
s = 'https://www.youtube.com/watch?v=FpJi6Pb_67s&t=3402s'
url = pyqrcode.create(s)
#Create and save the png file naming 'myqr.png'
url.svg('myyoutube.svg', scale = 8 )
print(url)

from google.colab import files
files.download('myyoutube.svg')

QRCode(content=b'https://www.youtube.com/watch?v=FpJi6Pb_67s&t=3402s', error='H', version=6, mode='binary')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [4]:
#Dice roll simulator
import random
#range of the values of the dice
max_val = 6
min_val = 1
# to loop the rolling through user input
roll_again = 'yes'
while roll_again == 'yes' or roll_again == 'y':
  print('Rolling the dices...')
  print('The values are: ')

  #generating and printing first random integer from 1 to 6
  print(random.randint(min_val, max_val))
  #generating and printing first random integer from 1 to 6
  print(random.randint(min_val, max_val))
  roll_again = input('Roll the dices again?')

Rolling the dices...
The values are: 
6
6
Roll the dices again?y
Rolling the dices...
The values are: 
1
5
Roll the dices again?yes
Rolling the dices...
The values are: 
4
5
Roll the dices again?n


In [5]:
import numpy as np

In [7]:
a = np.random.random((5,5,5))
print(a)

[[[0.84218111 0.87352241 0.39465331 0.56815504 0.47872437]
  [0.07812497 0.71344306 0.71662883 0.7069995  0.34227796]
  [0.94618416 0.49000425 0.26800862 0.45112733 0.55601505]
  [0.43139092 0.44426523 0.6052111  0.92996005 0.42296362]
  [0.88200679 0.95201589 0.63490701 0.042283   0.30073893]]

 [[0.34518035 0.03941581 0.83586688 0.04327819 0.70358964]
  [0.76689246 0.40655926 0.31360258 0.68292692 0.70964243]
  [0.26725297 0.55511084 0.57118497 0.94600535 0.01922229]
  [0.91039542 0.26701024 0.23880232 0.03385675 0.66229533]
  [0.81548961 0.98858879 0.52616964 0.48878941 0.61437575]]

 [[0.17871922 0.72930864 0.74984341 0.17353855 0.12130913]
  [0.86419211 0.4085802  0.38657748 0.61236158 0.86549536]
  [0.91308009 0.41978452 0.64703655 0.26115127 0.18240045]
  [0.74894033 0.0850424  0.87895942 0.69707113 0.55146892]
  [0.3527271  0.00484361 0.28571221 0.12308876 0.76165683]]

 [[0.23255859 0.51509889 0.87358574 0.6805667  0.36681318]
  [0.59781094 0.97688426 0.61696251 0.21380333 0.4

In [11]:
v= np.random.random((10,10))
v_max,v_min = v.max(), v.min()
print(v_max,v_min)
#0.9866038102709302 0.025508396249420584
#0.9688565412080112 0.020772293363335637
#0.9925083151044815 0.004391322570258316

0.9925083151044815 0.004391322570258316


In [14]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

0.5190003887688454


In [20]:
v= np.ones((10,10))
# print(v)
v[1:-1,1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
a = np.zeros((5,5))
a[1:-1,1:-1] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
v= np.ones((5,5))
print(v)
v=np.pad(v,pad_width=1,mode='constant', constant_values=9)
print(v)
#padding refers to the process of adding elements (usually zeros or a specific constant value) to the edges of the array.
#This is often done to extend the size of the array or to create a border around it.

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [39]:
np.nan #nan means null.In NumPy, "NaN" stands for "Not a Number." It is a special floating-point value that represents undefined or
#unrepresentable numerical results.NaN is often used to indicate missing or undefined data in numerical arrays.

nan

In [44]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [45]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
v = np.diag([1,2,3,4,5])
print(v)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [52]:
z = np.diag(1+np.arange(4),k=-1) #The k=-1 parameter specifies that the diagonal should be placed one position below the main diagonal.
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
