In [7]:
#Data -----> Model --------> Prediction

In [8]:
#Supervised Learning
#Unsupervised Learning
#Reinforcement Learning

In [37]:
#import load_iris function from datasets module
from sklearn.datasets import load_iris

In [38]:
#save 'bunch' object containing iris dataset and its attributes
iris =load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [39]:
print (iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [40]:
#Machine learning Terminology
#Each row is an observation (also known as:sample, example, instance, record)
#Each column is a feature(also known as: predictor, attribute, independent variable, input regressor, covariate)

In [41]:
#print the name of the four features(columns)
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [42]:
#Print integers representing the species of each observation (This refers to the number of observation)
#Target is also known as dependent variable or response variable
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [43]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [44]:
#Classification is supervised learning in which the response is categorical. (Dependent variable is categorical)

In [45]:
#Regression is supervised learning in which the response is ordered and continuous. (Dependent variable is ordered and continuous)

In [46]:
#Requirements for working with data in scikit-learn.
#Features (independent variable) and response (dependent variable) are separate objects.
#Features (independent variable) and response (dependent variable) should be numeric.
#Features (independent variable) and response (dependent variable) should be Numpy arrays.
#Features (independent variable) and response (dependent variable) should have specific shapes

In [47]:
#check the types of features adn response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [48]:
#Check the shape of the features (first dimension = number of observations, second dimensions = number of features)
print (iris.data.shape)

(150, 4)


In [49]:
#check the shape of the response (single dimension matching the number of observations)
print(iris.target.shape)

(150,)


In [61]:
#store feature matrix in 'X'. X is independent variable.
X= iris.data

#store response vector in 'y'. y is dependent variable.
y= iris.target

In [62]:
#Training machine learning model with scikit-learn
#Agenda:
# 1. What is the k-nearest neighbors classification model?
# 2. What are four steps for model training and prediction in scikit-learn?
# 3. How can I apply this pattern to other machine learning models?

In [52]:
#Reviewing the iris dataset
#150 observations.
# 4 features (independent variable).
# Response variable is the iris species.
# Classification problem since response is categorical.

In [53]:
#k-nearest neighbors (KNN) classification
#1. pick a value for K
#2. Search for the K observations in the training data that are 'nearest' to the measurements of the unknown iris.
#3. Use the most popular response value from the K nearest neighbors as the predicted response value for the unknown iris.

In [63]:
#print the shape of X and y
print (X.shape)#X is a two dimensional array with 150 rows and 4 columns.
print (y.shape)# y is a one dimensional array with length 150 since there is one response value for each observation.

(150, 4)
(150,)


In [55]:
# scikot-learn 4-step modeling pattern
# step 1: Import the class you plan to use (In this we import k neighbors classifier from sklearn.neighbors)

In [64]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#Step 2: 'Instantiate' the 'estimator'. Scikit-learn refers to its model as estimator because their primary role is to estimate unnown quantities.
# This process is called instantiation because we are creating instance of the KNeighbor classifier class.
# 'Estimator' is scikit-learn's term for model
# 'Instantiate' means 'make an instance of'

In [65]:
knn = KNeighborsClassifier(n_neighbors=1) #knn is an obejct here
#Name of the object does not matter
#Can specify tuning parameters (aka 'hyperparameters') during this step. n_ neighbor is known as tuning parameter or hyper parameter.
#All parameters not specified are set to their defaults.

In [66]:
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [ ]:
#Step 3: Fit the model with data (aka 'model training')
# Model is learning the relationship between X and y.
# Occurs in-place

In [67]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
#Step-4: Predict the response for new observation
# New observation is called 'out-of sample' data.
# Uses the information it learned during the model training process

In [69]:
knn.predict([[3,5,4,2]])#Predict is the method in Knn object.
#Returns a numpy array
# Can predit for multiple observations at once. #Here 2 is the encoding for 'Verginica'. So virginica is the predicted species for unknown iris.

array([2])

In [71]:
X_new = [[3,5,4,2],[5,4,3,2]] # 2 by 4 which mean 2 observations with four features each.
knn.predict(X_new)

array([2, 1])

In [76]:
#Using adifferent value for K
#initiate the model (using the value k = 5)
knn=KNeighborsClassifier (n_neighbors=5)

#Fit the model with data
knn.fit(X,y)

#Predict the response for new observations
knn.predict(X_new)

array([1, 1])

In [80]:
#Using a different classification model
#Import the class
from sklearn.linear_model import LogisticRegression

#Instantiate the model (using the default parameters)
logreg = LogisticRegression(solver='liblinear')

#fit the model with data
logreg.fit(X,y)

#Predict the respomse for new observations
logreg.predict(X_new)

array([2, 0])

In [ ]:
#Comparing Machine Learning models in scikit-Learn
#Agenda:
#1. How do i choose which model to use for my supervised learning task?
#2. How do I choose the best tuning parameters for that model?
#3. How do I estimate the likely performance of my model on out-of-sample data?

In [ ]:
#Review
# Classification task: Predicting the species of an unknown iris
# Used three classification models:KNN (k=1), KNN (K=5), LOGISTIC REGRESSION
# Need a way to choose between the models

# Solution: Model evaluation procedures

In [ ]:
#Evaluation Procedure #1: Train and test on the entire dataset
#1. Train the model on the entire dataset.
#2. Test the model on the same dataset, and evaluate how well we did by comparing the predicted response values with the true response values.

In [81]:
#read in the iris data
from sklearn.datasets import load_iris
iris = load_iris()

In [82]:
#Create X(features) and y (response)
X=iris.data
y=iris.target

In [86]:
#Logistic regression

#Import the class
from sklearn.linear_model import LogisticRegression

#Instantiate the model (using the default parameters)
logreg = LogisticRegression(solver='liblinear')

#Fit the model with data
logreg.fit(X,y)

#Predict the response values for the observation in X
logreg.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [88]:
#store the predicted response values
y_pred = logreg.predict(X)

#Check how many predictions were generated
len(y_pred)

150

In [ ]:
#Classification Accuracy:
  #1.Proportion of correct predictions
  #2.Common evaluation metric for classification problems

In [90]:
#Compute classification accuracy for the logistic regression model
from sklearn import metrics
print(metrics.accuracy_score(y,y_pred))

0.96


In [ ]:
# It shows that 96% of our predictions are correct. This is known as training accuracy because we are testing the model on the same data we use
# to train the model.

In [91]:
#KNN (K=5)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier (n_neighbors=5)
knn.fit(X,y)
y_pred = knn.predict(X)
print(metrics.accuracy_score(y,y_pred))

0.9666666666666667


In [92]:
#KNN (k=1)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X,y)
y_pred = knn.predict(X)
print(metrics.accuracy_score(y,y_pred))

1.0


In [ ]:
#Problems with training and testing on the same data
#1. Goal is to estimate likely performance of a model on out-of-sample data.
#2. But, maximizing training accuracy rewards overly complex models that won't necessarily generalize.
#3. Unnecessarily, complex models overfit the training data

In [ ]:
#Evaluation procedure #2:Train/test split
# 1. Split the data into two pieces: a training set and a testing set.
# 2. Train the modle on the training set.
# 3. Test the model on the testing set, and evaluate how well we did.

In [93]:
#print the shapws of X and y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [97]:
#Step 1: split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4, random_state=4) #40% of the observation to the testing set.

In [99]:
#print the shapes of the new X objects
print(X_train.shape)
print(X_test.shape)

(90, 4)
(60, 4)


In [100]:
#print the shapes of the new y objects
print(y_train.shape)
print(y_test.shape)

(90,)
(60,)


In [107]:
#Step 2: train the model on the training set
logreg = LogisticRegression(solver='liblinear')
logreg.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [108]:
#Step 3: Make predictions on the testing set
y_pred = logreg.predict(X_test)

#compare actual response values (y_test) with predicted response values (y_pred)
print(metrics.accuracy_score(y_test,y_pred))

0.9333333333333333


In [109]:
#Repeat for KNN WITH K=5:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9666666666666667


In [110]:
#Repeat for KNN WITH K=1:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.95


In [ ]:
#Downsides of train/test split?
#1. Provides a high-variance estimate of out-of-sample accuracy
#2. k-fold cross-validation overcomes this limitation
#3. But, train/test split is still useful because of its flexibility and speed
